version: '3.8'
services:
  todo-frontend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules 
    environment:
      - VITE_BACKEND_URL=http://localhost:3000 
    command: npm run dev 
