version: '3.8'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development

  backend:
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./backend:/app/backend
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
