version: '3.8'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

  frontend:
    image: todo-frontend:latest
  backend:
    image: todo-backend:latest
