version: '3.8'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

  frontend:
    build:
      context: ./todo-frontend
    environment:
      NODE_ENV: production
    depends_on:
      - backend

  backend:
    build:
      context: ./todo-backend
    environment:
      NODE_ENV: production
    depends_on:
      - redis
      - mongo

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
  redis_data:
  mongo_data:
